4plane:  vga svga

vga:
        del rc_high\display.rcv
        del rc_high\*.res
        cd vga
        $(MAKE)
   cd ..

svga:
        del rc_high\display.rcv
        del rc_high\*.res
        cd svga
        $(MAKE)
   cd ..
